### PR TITLE
Toggle to include/exclude upcoming/current season in threshold calculation.

### PR DESCRIPTION
**Pull request by aaron-kaplan**
The goal of this PR was to give the user control over whether the forecast for the upcoming season was included in the threshold calculation or not. While working on that I also did some refactoring, and changed to a different Bootstrap theme because the color choices of the one we were using seemed unconventional and disturbing. Please read commit-by-commit.

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
Currently running on http://shortfin01.iri.columbia.edu:9999/fbfmaproom/niger

**Comment by aaron-kaplan** [comment]
- [ ] Update export endpoint
- [ ] Fix tests
- [ ] Tooltip for checkbox
- [ ] Fix column alignment and cell padding

**Comment by aaron-kaplan** [comment]
I got the checkbox in the table working, but the code was messy. I worked on cleaning it up for a while, but it became apparent that it would take more work than it was worth, given that we didn't intend to keep that UI forever. So I moved the checkbox to the table controls, which in retrospect is probably where Dan would have wanted it in the first place.

I've retained some of the refactoring I did while trying to get the messy version cleaned up. Best read commit-by-commit.

@kgraaf please review.

**Comment by aaron-kaplan** [comment]
Dan has approved. @kgraaf please review.

**Comment by aaron-kaplan** [comment]
@kgraaf this has been waiting for your review for over two weeks. Please finish reviewing.

**Review by kgraaf — APPROVED** [review]

**Pull request merged**
