### PR TITLE
WSRI+NDVI ond,djf for lesotho

### PR DESCRIPTION
**Pull request by xchourio**

### CODE REVIEW

**Comment by xchourio** [comment]
@aaron-kaplan I tested it in a local run and it displayed both variables well, but I haven't updated the 'public test server' yet because the FIST team shared that link with partner institutions while waiting for their approval for other countries' maprooms. So, I avoided making the update.

**Comment by aaron-kaplan** [comment]
Please share it on your internal test server on shortfin01.

The external test server and the shortfin dev setup share the same storage, but not the same config files, so you can add a new dataset to the shortfin01 server without making it visible to the partner.

**Review by aaron-kaplan — APPROVED** [review]
Looks good,  pending FIST's apporoval.

**Comment by xchourio** [comment]
The comment from Nitin Magima in Trello leads me to understand that we have FIST approval. I'll merge it.

**Pull request merged**
