### PR TITLE
Simple sphinx setup

### PR DESCRIPTION
**Pull request by aaron-kaplan**
This is a quick-and-dirty setup to let people get started writing sphinx-formatted docstrings. For now it only builds docs for files in onset_maproom. We will extend it to cover pingrid.py etc. later, after rearranging the repo.

Build instructions have been added to README.md, and I started (didn't finish) enriching the docstring for `seasonal_onset_date` as an example.

I'm "throwing this over the wall" just before leaving on vacation. Feel free to discuss and edit among the three of you and then merge when you're ready.

### CODE REVIEW

**Comment by remicousin** [comment]
@kgraaf , should we merge this so that Drew and I branch from the merged master to add their content, and possibly refine the configuration as we discover how it works? The alternative is that we both work on that branch here but that has proven to be a slightly tedious in the past.

**Comment by drewmresnick** [comment]
@remicousin Yes I would prefer not to work on the same branch again so I would rather merge this one as soon as it's ready. To be fair though I am writing the documentation regardless so I am not in a huge rush but it would be nice to have this merged.

**Comment by remicousin** [comment]
Push your work on your branch as you go so that I know which ones you have done. You can always set up the PR later. When I start, I'll let you know which ones I start with.

**Review by remicousin — APPROVED** [review]

**Comment by drewmresnick** [comment]
@remicousin is there a way to push a new branch without setting up the PR when first pushing? I am not familiar with how to do that if so.

**Comment by remicousin** [comment]
yes. You just push as you would do to set the PR, except you don't go to gitHub website to set the PR. Then when you are ready to set up the PR, you go to github, go to Code, select your branch, and then somewhere you'll have a button to set up the PR.
I think you can also set the PR as you usually do after pushing and just don't assign any reviewers, that should also be a clear sign that your work is nobody's business as of now :)

**Comment by drewmresnick** [comment]
Okay [here](https://github.com/iridl/python-maprooms/commit/f3cb872616a8b7e445062d052c607f9c96f7dcff) is the commit on my branch. I tried to write something for all of the functions, since I had already started. Once we merge this branch Aaron made, and I rebase and check how it all compiles I can open the PR. Then if you would like, you can just give me improvements on the documentation I have already wrote so we are not both writing the documentation on different branches? Or we can proceed in a different way if you'd like, just let me know what you think.

Are we waiting for @kgraaf's approval on this to merge? I don't know much about sphinx yet to feel like I can approve or not..

**Review by kgraaf — APPROVED** [review]

**Comment by kgraaf** [comment]
I went ahead and approved. Let me know if you would like me to merge or if you want to.

**Comment by drewmresnick** [comment]
@kgraaf I can go ahead and merge it. Thanks for approving

**Pull request merged**
