### PR TITLE
added jjaso forecast

### PR DESCRIPTION
**Pull request by kgraaf**

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
Looks good. Please set up an internal test server so we can see what it looks like. You can announce it to me and to FIST at the same time.

**Comment by aaron-kaplan** [comment]
Test server is here http://devi.iri.columbia.edu:8077/fbfmaproom/niger

**Review by aaron-kaplan — APPROVED** [review]
LGTM but wait for Dan's approval before merging and deploying.

**Comment by kgraaf** [comment]
Do we need FIST's imprimatur to publish or can we go head if it looks good to you as with the other data sets I/we added?

**Comment by kgraaf** [comment]
Beat me to it

**Pull request merged**
