### PR TITLE
Add madagascar DJF V2

### PR DESCRIPTION
**Pull request by xchourio**

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
Thanks Xandre. My test server is now running from this branch: http://shortfin01.iri.columbia.edu:9999/fbfmaproom/madagascar

I will share it with FIST for their review.

**Comment by aaron-kaplan** [comment]
Dan approved, but we can't merge this because there are conflicts. @xchourio please resolve them, and let me know if you need help.

**Comment by xchourio** [comment]
> Dan approved, but we can't merge this because there are conflicts. @xchourio please resolve them, and let me know if you need help.

I resolved the conflicts

**Comment by aaron-kaplan** [comment]
Github says there are still conflicts. See below. I think it's because the last line of the file has been modified on master, and you added a new line at the end. To resolve, you must either rebase this branch onto master, or merge master into this branch.

image

You could also try clicking the "Resolve conflicts" button in the picture to resolve it in the github web interface.

**Comment by xchourio** [comment]
> Github says there are still conflicts. See below. I think it's because the last line of the file has been modified on master, and you added a new line at the end. To resolve, you must either rebase this branch onto master, or merge master into this branch.
> 
> image
> 
> You could also try clicking the "Resolve conflicts" button in the picture to resolve it in the github web interface.

I repeated the process in a ((no branch, rebasing xchourio/madagascar-djf)), now all shows in green in Github

**Review by aaron-kaplan — APPROVED** [review]

**Pull request merged**
