### PR TITLE
Niger monitoring

### PR DESCRIPTION
**Pull request by kgraaf**

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
LGTM, but we should wait for confirmation from FIST before pushing to prod.

**Review by aaron-kaplan — APPROVED** [review]

**Comment by aaron-kaplan** [comment]
I have installed the dataset in /data/aaron/fbf-candidate and /data/aaron/fbf, so as soon as FIST approves you can merge and make the config change in dlconfig.

**Comment by aaron-kaplan** [comment]
We got the green light in today's FIST meeting. The data are already in place in /data/aaron/fbf. @kgraaf merge and deploy at your convenice.

**Comment by kgraaf** [comment]
Merged and deployed to prod

**Pull request merged**
