### PR TITLE
Madagascar OND v2

### PR DESCRIPTION
**Pull request by xchourio**

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
Please update the label and description of the v1 forecast dataset too. (Don't change the yaml key `pnep`, that has to stay the same, but you can change the values of the `label` and `description` attributes.)

**Comment by xchourio** [comment]
> Please update the label and description of the v1 forecast dataset too. (Don't change the yaml key `pnep`, that has to stay the same, but you can change the values of the `label` and `description` attributes.)

Done!

**Review by aaron-kaplan — APPROVED** [review]

**Comment by aaron-kaplan** [comment]
When it's time to push the change to the public server (after FIST approves), please make the same change in a dlconfig PR.  https://bitbucket.org/iridl/dlconfig/src/master/ansible/configs/fbfmaproom2/fbfmaproom.yaml

**Comment by aaron-kaplan** [comment]
We never got all the data files we asked for.

**Pull request closed without merging**
