### PR TITLE
Multipage ENACTS maproom

### PR DESCRIPTION
**Pull request by aaron-kaplan**
Merges forecast, onset, and monthly climo maprooms into a single application. Working configuration for zmd for all three.

I haven't tested the Dockerfile yet (and I see a mistake in it as I'm writing this), but the application runs in the dev environment.

I use this convenient command to launch it:

```
FLEX_FCST_CONFIG=flex_fcst/config-sample.yaml:flex_fcst/config-zmd.yaml:config.yaml ONSET_CONFIG=onset/config-sample.yaml:onset/config-zmd.yaml:config.yaml MONTHLY_CONFIG=monthly/config-sample.yaml:monthly/config-zmd.yaml:config.yaml python homepage.py
```
where config.yaml is a file that contains the following
```
db:
    password: abcde
```
(substitute the actual password for abcde).

My initial plan was to use the version of the monthly maproom from iridl/lms-monthly, the one Drew and I worked on cleaning up last week, but in the end I used Kevin's version from the KMD server (including non-checked-in-changes) as my starting point, because that version no longer requires pre-computed climatologies to be downloaded from Ingrid. That means I'll have to go back through the history of iridl/lms-monthly and re-apply all the changes we want to keep.

Demo running here: http://devi.iri.columbia.edu:5000/python-maproom/

I suggest that @remicousin and @drewmresnick concentrate on testing the application  rather than reviewing the code. @kgraaf can review to the extent possible, but we're supposed to get this running by Monday.

@remicousin you could work on getting it running at ZMD, if you think there's any chance their server will be on line in time.

### CODE REVIEW

**Comment by remicousin** [comment]
I have checked this out on my clone on 211. Started a config.yaml and running a couple of issues:
1/ I am creating the dekadal zarr files now: I hadn't a script for that before
2/ I don't know what to put for the db's host and port. I tried localhost for host, what may or may not be correct, but then it didk't like the default port, and for that one I have no lead on what to try.

Note I made a multipage-mr environment for this. I wanted to test on the dedicated 211 server to try kill a couple of birds in one stone, #1 will be resolves soon, but I can't resolve #2. I'll test on the link provided by Aaron in the meantime

**Comment by aaron-kaplan** [comment]
Oh yeah, Kevin made a change on the KMD server to allow a development
server to talk to the db. I guess you can't test it until I do that.

**Comment by remicousin** [comment]
Set default month for Cessation date search start as March

**Comment by remicousin** [comment]
The phrase that prints the name of the District being moused over (Onset Maproom only) is hidden behind the tabs with the graphics (it's right under the map title (sorry: that's probably my poor html skills...)

**Comment by remicousin** [comment]
Actually I am not sure I am seeing the bottom of the graphs.

**Comment by remicousin** [comment]
Remember the weird bug we never fixed about the cumulative graphs making weird bumps? I think I get it now. Or a similar bug I am seeing now: Searching for onset in Zambia starts maybe November 1st. When the algo finds a date into the next year, say in January, the graphics (both time series and cumulative) don't get that it's the next year, and so the Jan values are considered way earlier as opposed to a bit further.

Maybe I should look into that now? If so, should I push here or make another PR?

**Comment by remicousin** [comment]
Need a spin for map reloading otherwise users/trainees are likely going to click like nuts if they don't see anything changing.

**Comment by aaron-kaplan** [comment]
> When the algo finds a date into the next year, say in January, the graphics (both time series and cumulative) don't get that it's the next year, and so the Jan values are considered way earlier as opposed to a bit further.

Sounds plausible. You can push to this branch.

**Comment by aaron-kaplan** [comment]
Just don't force-push to this branch please.

**Comment by aaron-kaplan** [comment]
If you have nothing else to do you could also address some of your other comments. I'll focus on getting it running on the ZMD server, and then come back and fix whatever you weren't able to.

**Comment by remicousin** [comment]
I will finish my review then. Putting comments here. Then depending on the time, we'll try start addressing.

**Comment by drewmresnick** [comment]
Anything I might be able to help with here?

**Comment by aaron-kaplan** [comment]
@drewmresnick you could work on addressing any of Rémi's comments. Post a note here when you start on a new task so we don't duplicate effort.

**Comment by drewmresnick** [comment]
Okay.

@aaron-kaplan Just to make sure I remember working on the same branch together, so as not to make anything messy..

after I `git fetch` the branches, and `git checkout multipage` then I can do some work and `git commit`. 
When I am ready to push I just do a regular `git push origin multipage` to this branch.
If others make changes that they push to the branch I would do `git pull origin multipage` while on the branch?
Is there anything else or any of those things I got wrong?

**Comment by aaron-kaplan** [comment]
git pull --rebase origin multipage. Other than that, sounds right.

**Comment by drewmresnick** [comment]
@aaron-kaplan So I am trying to run the maproom remotely over the server using the vpn and when I try to load the page, it is blank. Maybe I could get some help with this. (for reference I am ssh'ing onto the server, first I tried `ssh -L 8050:localhost:8050 server`

When I run the app I get that it is running on http://127.0.0.1:5000/

Things I tried:
1. append `/python_maproom/` to the end of the url like so `http://127.0.0.1:5000/python_maproom`
2. change port to 8050 in the url
3. change the port from 8050 to 5000 when ssh'ing onto the server

I am not super comfortable figuring out issues with ports/addresses so those were just some shots in the dark.

**Comment by aaron-kaplan** [comment]
In `ssh -L A:localhost:B server`, `A` is the port on your computer that you will visit in the browser, and `B` is the port on the server that it will be forwarded to.

In the case you described, the application is listening on port 5000 but you're forwarding your browser to port 8050, so they don't connect.

**Comment by drewmresnick** [comment]
Okay I got it to work, I guess the first time I tried changing the ports in the ssh command I must have typed it incorrectly or something..

I wonder though why when the app runs it does not point you to http://127.0.0.1:5000/python_maproom/ and instead just says `Running on http://127.0.0.1:5000/`. Is there a way to point to the home page?

**Comment by drewmresnick** [comment]
> Set default month for Cessation date search start as March

I am working on this.

**Comment by remicousin** [comment]
Seasonal Forecast Maproom title should be titled "seasonal," Tufa reports it's titled "subseasonal.

**Comment by remicousin** [comment]
> Remember the weird bug we never fixed about the cumulative graphs making weird bumps? I think I get it now. Or a similar bug I am seeing now: Searching for onset in Zambia starts maybe November 1st. When the algo finds a date into the next year, say in January, the graphics (both time series and cumulative) don't get that it's the next year, and so the Jan values are considered way earlier as opposed to a bit further.
> 
> Maybe I should look into that now? If so, should I push here or make another PR?

I am going to try and fix this now.

**Comment by remicousin** [comment]
> Okay I got it to work, I guess the first time I tried changing the ports in the ssh command I must have typed it incorrectly or something..
> 
> I wonder though why when the app runs it does not point you to http://127.0.0.1:5000/python_maproom/ and instead just says `Running on http://127.0.0.1:5000/`. Is there a way to point to the home page?

I am sorry: I didn't quite get all that. How do I run the app on devi? how are things different than before?

**Comment by aaron-kaplan** [comment]
Edit the last line of homepage.py, adding `host=0.0.0.0, port=1234` (each of us needs to pick a different port). Then use the long command I gave in the PR description to run it.

I plan to consolidate the config, but that's not urgent.

**Comment by remicousin** [comment]
got it. I am 8063

**Comment by aaron-kaplan** [comment]
The biggest performance problem is that we were using 40MB of shapes, which takes a long time to transmit over a slow connection. I've addressed that for now by simplifying the shapes to a fixed .01 degree resolution. A more complete solution for the future will be to simplify to whatever the tile pixel resolution is, which depends on the zoom level.

I also removed "subseasonal" from the title and text, and added clipping to all the maps for consistency. I made the default zoom one level higher to address Tufa's complaint about too much space outside the country being displayed.

@remicousin could you review my new commits? And let me know if you think you'll fix the cessation plot in the next few hours, i.e. whether I should deploy to the ZMD server now or wait for your change.

**Comment by remicousin** [comment]
I am almost there. struggling to add days to a date right now but that should be the last step...

**Comment by remicousin** [comment]
ok. I am done. Will review your changes. Then apply my work to the cessation graphs, wait for your commits, pull and push

**Comment by remicousin** [comment]
My changes on top of yours seem to work all fine. The admin drawing worked fine. Indeed things seem to be coming up faster.

As for my changes, I had to have the axes working on deltas (can't do the maths on dates) and I used the hovertemplate to allow to show dates. I might have redone more than necessary because in the interest of time pressure, I reverted to things I already know how they work (e.g. types of graphs); to cut on confounding factors when debugging...

**Comment by aaron-kaplan** [comment]
Looks good. Ready to approve?

**Review by remicousin — APPROVED** [review]

**Pull request merged**
