### PR TITLE
FBF: Fix vuln colorscale--opencv expects bgr not rgb.

### PR DESCRIPTION
**Pull request by aaron-kaplan**
I guess I forgot to test the vulnerability layer before approving the colormap change. It's currently displaying shades of blue rather than shades of yellow/orange.

### CODE REVIEW

**Review by remicousin — APPROVED** [review]
I haven't interfered with this apply_mask function so I assume you know what it is up to.

**Comment by aaron-kaplan** [comment]
You did change it here: https://github.com/iridl/python-maprooms/pull/246/files#diff-7e36d4e5a9d8a7b6255214ee91840aa2ece17c138a346dc1656535d142675c1fR563

That change replaces a BGRA with a Color (which is RGB). That value gets converted to a numpy array and passed to opencv, which expects BGRA.

**Comment by aaron-kaplan** [comment]
This may not be correct, or complete. Now I get yellows instead of blues, but the map still looks quite different from the original. I have a feeling the scale may be inverted. I'll have to look into it more on Monday.

**Comment by remicousin** [comment]
I will try to as well. Unlikely today.

**Comment by remicousin** [comment]
The thing is that I never knew how to make the Vulnerability map appear so on that front, my "testing" was only on the colorbar...

**Comment by aaron-kaplan** [comment]
I tried the same confirmation again today and what I see from this branch looks identical to what's in production. I suspect I accidentally selected different years when I attempted to compare last week.

**Pull request merged**
